services:
  - type: web
    name: talentsync-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ML_SERVICE_URL
        sync: false
      - key: AFFINDA_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: talentsync-ml
    runtime: python
    rootDir: ML_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
